### ISSUE TITLE
Ankaufsrechnungen, z.B. No. "463091", pers. am Tresen u. per Post

### ISSUE THREAD

**Issue by SCoHHGit** [chrbusch/HeavyMetal#22]

**Comment by SCoHHGit** [comment]
[AKR Ankaufsgutschrift Privat.pdf](https://github.com/chrbusch/HeavyMetal/files/3971021/AKR.Ankaufsgutschrift.Privat.pdf)
[AKR Ankaufsgutschrift Privat mehr Artikel.pdf](https://github.com/chrbusch/HeavyMetal/files/3971022/AKR.Ankaufsgutschrift.Privat.mehr.Artikel.pdf)

Gewerbekunden verkaufen an uns mit anderen Konditionen... Für Gewerbekunden müssen wir bei erreichen eines bestimmten Warenwertes die Mehrwertsteuer abführen, damit mit der ausgezahlten Mehrwertsteuer (wie früher) kein MwSt.-Betrug mehr erfolgen kann... Auf den diesbezüglichen Paragraphen weist eine Zeile in der folgenden Ankaufsrechnung hin. 

[AKR Ankaufsgutschrift Gewerblich.pdf](https://github.com/chrbusch/HeavyMetal/files/3971026/AKR.Ankaufsgutschrift.Gewerblich.pdf)

Wir haben die unterschiedliche Behandlung von Privat- und Gewerbekunden über unterschiedliche Ankaufsartikel (mit abweichenden Bedingungen) organisiert. So heißen unsere beiden Ankaufsartikel für Zahngold z.B. für Privatkunden AUZAHN oder AUSPAR. Die gleichen Artikel heißen für Gewerbekunden AUZAHNA und AUSPARA... oder auch AUA... oder AU750BRA... Diese Artikel lösen die Zeile in der Ankaufsrechnung aus :... 
"Laut Änderungsgesetz von § 13b Absatz 2 Nr. 7 geht ab dem 01.01.2011 die Steuerschuldner- schaft beim Ankauf von Edelmetallen oder Edelmetalllegierungen auf den Leistungs- empfänger über."

**Comment by chrbusch** [comment]
Ich bin dafür, ALLE Adressen in der entspr. Tabelle anzulegen, also auch private Verkäufer.
Ich würde dann zB das Datenfeld "AusweisNr" in der Tabelle Adresse definieren.
Betritt ein Verkäufer das Kontor, wird sein Adressen-DS gesucht bzw. neu angelegt.
Seine Quittungen finden sich dann in seiner Akte.

**Comment by chrbusch** [comment]
Was Sie oben schreiben, gehört eigentlich ins Ticket "Annahme..."! Wir sollten in einem Ticket jeweils ein Modul abarbeiten, sonst wird es zu unübersichtlich.

**Comment by SCoHHGit** [comment]
> Was Sie oben schreiben, gehört eigentlich ins Ticket "Annahme..."! Wir sollten in einem Ticket jeweils ein Modul abarbeiten, sonst wird es zu unübersichtlich.

Hier ist mir wichtig, dass wir den Ankauf, den Verkauf und die Anlieferung von Scheidgut unterscheiden, aber das könnten wir natürlich auch in einem Ticket. Ansonsten haben wir noch Feinmetallauslieferungen und Anlieferungen, die physisch erfolgen und weder Ankauf noch Verkauf darstellen. An- und Auslieferungen können aber auch über GIRO-Meldungen erfolgen. DAS wiederum würde ich auf jeden Fall bei den ANLIEFERUNGEN unter dem betreffenden Ticket behandeln. Können wir ja gleich besprechen.
